using Microsoft.EntityFrameworkCore;
using Npgsql;
using System.Security.Cryptography;

var builder = WebApplication.CreateBuilder(args);

var dbPassword =
    Environment.GetEnvironmentVariable("SUPABASE_DB_PASSWORD");

if (string.IsNullOrWhiteSpace(dbPassword))
{
    throw new Exception(
        "SUPABASE_DB_PASSWORD environment variable is not set.");
}

var adminApiKey =
    Environment.GetEnvironmentVariable("ADMIN_API_KEY");

if (string.IsNullOrWhiteSpace(adminApiKey))
{
    throw new Exception(
        "ADMIN_API_KEY environment variable is not set.");
}

var connectionStringBuilder =
    new NpgsqlConnectionStringBuilder
    {
        Host = "aws-1-eu-west-1.pooler.supabase.com",
        Port = 5432,
        Database = "postgres",
        Username = "postgres.tsnbteyvzgcqacvohtzz",
        Password = dbPassword,
        SslMode = SslMode.Require
    };

builder.Services.AddDbContext<LicenseDbContext>(
    options =>
        options.UseNpgsql(
            connectionStringBuilder.ConnectionString));

var app = builder.Build();


// =========================
// CREATE DATABASE TABLE
// =========================

using (var scope = app.Services.CreateScope())
{
    var db =
        scope.ServiceProvider
            .GetRequiredService<LicenseDbContext>();

    db.Database.ExecuteSqlRaw("""
        CREATE TABLE IF NOT EXISTS "LicenseKeys"
        (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "Key" character varying(50) NOT NULL,
            "IsUsed" boolean NOT NULL DEFAULT FALSE,
            "DeviceId" character varying(255),
            "ActivatedAt" timestamp with time zone,
            "CreatedAt" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
        );

        CREATE UNIQUE INDEX IF NOT EXISTS "IX_LicenseKeys_Key"
        ON "LicenseKeys" ("Key");
        """);
}


// =========================
// HOME
// =========================

app.MapGet("/", () =>
{
    return Results.Ok(new
    {
        service = "Diner Crepe License Server",
        status = "online"
    });
});


// =========================
// CREATE LICENSE KEYS
// =========================

app.MapPost(
    "/api/license/create",
    async (
        HttpRequest httpRequest,
        LicenseDbContext db,
        int count) =>
{
    if (!IsAdminAuthorized(httpRequest, adminApiKey))
    {
        return Results.Unauthorized();
    }

    if (count < 1 || count > 1000)
    {
        return Results.BadRequest(new
        {
            success = false,
            message =
                "عدد المفاتيح يجب أن يكون بين 1 و1000."
        });
    }

    var keys =
        new List<string>();

    for (int i = 0; i < count; i++)
    {
        string key;

        do
        {
            key =
                GenerateLicenseKey();
        }
        while (
            await db.LicenseKeys
                .AnyAsync(x => x.Key == key));

        db.LicenseKeys.Add(
            new LicenseKey
            {
                Key = key,
                IsUsed = false,
                CreatedAt = DateTime.UtcNow
            });

        keys.Add(key);
    }

    await db.SaveChangesAsync();

    return Results.Ok(new
    {
        success = true,
        count = keys.Count,
        keys
    });
});


// =========================
// GET ALL LICENSES
// =========================

app.MapGet(
    "/api/license/all",
    async (
        HttpRequest httpRequest,
        LicenseDbContext db) =>
{
    if (!IsAdminAuthorized(httpRequest, adminApiKey))
    {
        return Results.Unauthorized();
    }

    var licenses =
        await db.LicenseKeys
            .OrderByDescending(
                x => x.CreatedAt)
            .Select(x => new
            {
                id = x.Id,
                key = x.Key,
                isUsed = x.IsUsed,
                deviceId = x.DeviceId,
                createdAt = x.CreatedAt,
                activatedAt = x.ActivatedAt
            })
            .ToListAsync();

    return Results.Ok(new
    {
        success = true,
        count = licenses.Count,
        licenses
    });
});


// =========================
// ACTIVATE LICENSE
// =========================

app.MapPost(
    "/api/license/activate",
    async (
        LicenseDbContext db,
        ActivateLicenseRequest request) =>
{
    if (string.IsNullOrWhiteSpace(request.Key))
    {
        return Results.BadRequest(new
        {
            success = false,
            message = "مفتاح الترخيص مطلوب."
        });
    }

    if (string.IsNullOrWhiteSpace(request.DeviceId))
    {
        return Results.BadRequest(new
        {
            success = false,
            message = "معرف الجهاز مطلوب."
        });
    }

    string normalizedKey =
        request.Key
            .Trim()
            .ToUpperInvariant();

    string deviceId =
        request.DeviceId.Trim();

    var license =
        await db.LicenseKeys
            .FirstOrDefaultAsync(
                x => x.Key == normalizedKey);

    if (license == null)
    {
        return Results.Ok(new
        {
            success = false,
            message =
                "مفتاح الترخيص غير صحيح."
        });
    }

    if (license.IsUsed)
    {
        if (string.Equals(
                license.DeviceId,
                deviceId,
                StringComparison.Ordinal))
        {
            return Results.Ok(new
            {
                success = true,
                message =
                    "الترخيص مفعل بالفعل على هذا الجهاز.",
                activatedAt =
                    license.ActivatedAt
            });
        }

        return Results.Ok(new
        {
            success = false,
            message =
                "هذا المفتاح مرتبط بجهاز آخر."
        });
    }

    license.IsUsed = true;
    license.DeviceId = deviceId;
    license.ActivatedAt =
        DateTime.UtcNow;

    await db.SaveChangesAsync();

    return Results.Ok(new
    {
        success = true,
        message =
            "تم تفعيل البرنامج بنجاح.",
        activatedAt =
            license.ActivatedAt
    });
});


// =========================
// VALIDATE LICENSE
// =========================

app.MapPost(
    "/api/license/validate",
    async (
        LicenseDbContext db,
        ValidateLicenseRequest request) =>
{
    if (string.IsNullOrWhiteSpace(request.Key))
    {
        return Results.BadRequest(new
        {
            success = false,
            message =
                "مفتاح الترخيص مطلوب."
        });
    }

    if (string.IsNullOrWhiteSpace(request.DeviceId))
    {
        return Results.BadRequest(new
        {
            success = false,
            message =
                "معرف الجهاز مطلوب."
        });
    }

    string normalizedKey =
        request.Key
            .Trim()
            .ToUpperInvariant();

    string deviceId =
        request.DeviceId.Trim();

    var license =
        await db.LicenseKeys
            .FirstOrDefaultAsync(
                x => x.Key == normalizedKey);

    if (license == null)
    {
        return Results.Ok(new
        {
            success = false,
            message =
                "مفتاح الترخيص غير صحيح."
        });
    }

    if (!license.IsUsed)
    {
        return Results.Ok(new
        {
            success = false,
            message =
                "هذا المفتاح لم يتم تفعيله بعد."
        });
    }

    if (!string.Equals(
            license.DeviceId,
            deviceId,
            StringComparison.Ordinal))
    {
        return Results.Ok(new
        {
            success = false,
            message =
                "هذا المفتاح مرتبط بجهاز آخر."
        });
    }

    return Results.Ok(new
    {
        success = true,
        message =
            "الترخيص صالح.",
        activatedAt =
            license.ActivatedAt
    });
});


// =========================
// SERVER PORT
// =========================

var port =
    Environment.GetEnvironmentVariable("PORT")
    ?? "10000";

app.Run(
    $"http://0.0.0.0:{port}");


// =========================
// ADMIN AUTHORIZATION
// =========================

static bool IsAdminAuthorized(
    HttpRequest request,
    string adminApiKey)
{
    if (!request.Headers.TryGetValue(
            "X-Admin-Key",
            out var suppliedKey))
    {
        return false;
    }

    return string.Equals(
        suppliedKey.ToString(),
        adminApiKey,
        StringComparison.Ordinal);
}


// =========================
// LICENSE KEY GENERATOR
// =========================

static string GenerateLicenseKey()
{
    const string chars =
        "ABCDEFGHJKLMNPQRSTUVWXYZ23456789";

    string CreatePart()
    {
        var bytes =
            RandomNumberGenerator.GetBytes(4);

        var result =
            new char[4];

        for (int i = 0; i < 4; i++)
        {
            result[i] =
                chars[
                    bytes[i] % chars.Length];
        }

        return new string(result);
    }

    return
        $"DCP-{CreatePart()}-{CreatePart()}-{CreatePart()}";
}


// =========================
// DATABASE
// =========================

public class LicenseDbContext : DbContext
{
    public LicenseDbContext(
        DbContextOptions<LicenseDbContext> options)
        : base(options)
    {
    }

    public DbSet<LicenseKey> LicenseKeys =>
        Set<LicenseKey>();

    protected override void OnModelCreating(
        ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<LicenseKey>(
            entity =>
            {
                entity.ToTable("LicenseKeys");

                entity.HasKey(x => x.Id);

                entity.Property(x => x.Key)
                    .IsRequired()
                    .HasMaxLength(50);

                entity.HasIndex(x => x.Key)
                    .IsUnique();

                entity.Property(x => x.IsUsed)
                    .IsRequired();

                entity.Property(x => x.DeviceId)
                    .HasMaxLength(255);

                entity.Property(x => x.CreatedAt)
                    .IsRequired();
            });
    }
}


// =========================
// LICENSE MODEL
// =========================

public class LicenseKey
{
    public int Id { get; set; }

    public string Key { get; set; } = "";

    public bool IsUsed { get; set; }

    public string? DeviceId { get; set; }

    public DateTime? ActivatedAt { get; set; }

    public DateTime CreatedAt { get; set; } =
        DateTime.UtcNow;
}


// =========================
// ACTIVATE REQUEST
// =========================

public class ActivateLicenseRequest
{
    public string Key { get; set; } = "";

    public string DeviceId { get; set; } = "";
}


// =========================
// VALIDATE REQUEST
// =========================

public class ValidateLicenseRequest
{
    public string Key { get; set; } = "";

    public string DeviceId { get; set; } = "";
}